{% set name = "openff-toolkit" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-toolkit/archive/{{ version }}.tar.gz
  sha256: 2c94b79417d1217b15b68f40c09278d7c9e428e5527f928c8c29651ee07fbbb5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - numpy
    - smirnoff99frosst
    - openff-forcefields
    - openmm
    - networkx
    - rdkit
    - ambertools >=20
    - mdtraj
    - xmltodict
  run_constrained:
    - openforcefield ==9999999999

test:
  imports:
    - openff.toolkit

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern, extensible library for molecular mechanics force field science from the Open Force Field Initiative
  description: |
    The Open Force Field Toolkit, built by the Open Force Field Initiative, is a Python
    toolkit for the development and application of modern molecular mechanics force fields
    based on direct chemical perception and rigorous statistical parameterization methods.
  doc_url: https://open-forcefield-toolkit.readthedocs.io/
  dev_url: https://github.com/openforcefield/openff-toolkit

extra:
  recipe-maintainers:
    - jaimergp
    - j-wags
    - mattwthompson
